name: Build and Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-latest
            platform: windows
            arch: x64
          - os: macos-latest
            platform: macos
            arch: x64
          - os: macos-latest
            platform: macos
            arch: arm64
            
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -e .
        
    - name: Install GUI dependencies (Linux)
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Build executable
      run: |
        python build.py
        
    - name: Test executable (Linux/macOS)
      if: matrix.platform != 'windows'
      run: |
        chmod +x dist/base-converter-*
        ./dist/base-converter-* --list-bases
        
    - name: Test executable (Windows)
      if: matrix.platform == 'windows'
      run: |
        .\dist\base-converter-*.exe --list-bases
        
    - name: Create release package
      shell: bash
      run: |
        mkdir -p release
        cp dist/base-converter-* release/
        cp install-*.* release/ 2>/dev/null || true
        cp PACKAGE_INFO.txt release/
        
        # Create archive
        if [ "${{ matrix.platform }}" = "windows" ]; then
          cd release && 7z a ../base-converter-${{ matrix.platform }}-${{ matrix.arch }}.zip *
        else
          tar -czf base-converter-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz -C release .
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: base-converter-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          base-converter-${{ matrix.platform }}-${{ matrix.arch }}.*
          
  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.create_release == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name || 'manual-release' }}
        name: Base Converter ${{ github.ref_name || 'Manual Release' }}
        body: |
          ## Base Converter Release
          
          A comprehensive cross-platform base conversion utility.
          
          ### Features
          - Convert between bases 2-36
          - Command-line and graphical interfaces  
          - Arithmetic operations in different bases
          - Batch processing capabilities
          - Input validation and error handling
          
          ### Downloads
          Choose the appropriate package for your platform:
          - **Windows**: Download `base-converter-windows-x64.zip`
          - **macOS**: Download `base-converter-macos-x64.tar.gz` or `base-converter-macos-arm64.tar.gz`
          - **Linux**: Download `base-converter-linux-x64.tar.gz`
          
          ### Installation
          1. Download the appropriate package
          2. Extract the archive
          3. Run the installer script or copy the executable to your PATH
          
          ### Usage
          ```bash
          # GUI mode
          base-converter --gui
          
          # CLI mode
          base-converter 1010 -f 2 -t 10    # Binary to decimal
          base-converter FF -f 16 -t 2      # Hex to binary
          base-converter --help             # Show help
          ```
          
          For more information, see the [README](https://github.com/6639835/base-converter/blob/main/README.md).
          
        draft: false
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        files: |
          base-converter-*.*
